* knives: 
    best santuko (a bit larger than average) 
    mac superior

* RECOMMENDS
kidde fire extinguishers 
for kitchen use smaller size
for survival, larger size

Oven temperature insertion thermometers:
    polder
    thermoworks
    buy lots of probes

acai,goji berries -- find source
tamari in place of soy sauce, no wheat, often low salt
eatwild.com
localharvest.org
westonaprice.org
  Clark County: Nancy Jo Newman (360) 606-9628, njonewman@earthlink.net
  Portland: Sharon & Warren Moliken (503) 545-7103, pdxwapf@gmail.com

* EATING APPLES:
  top 4:
    jonagold jonathan pink-lady macoun
  2nd 4:
    golden-delicious mcintosh empire rome


* MEAT LOAF
1 lb 80% beef (ground chuck)
1/2 lb veal
1/2 lb pork
2/3 cup Quaker Oats for binder
1/2 cup milk
egg(s)
1/2 cup milk
salt pepper dried_thyme worcesterchier dijon_mustard tobasco
Onions and garlic (could saute)

combine & form into log
1/3 cup parsley

as you mix, shouldn't stick to the bowl, adjust wetness
freeform on alum. on flat roasting pan
crust: catsup with moderate brown_sugar vinegar
wrap in bacon
reduce after applying crust

Oven 350 for an hour to achieve 160

for all beef:
50% 1 lb each surloin & chuck & grind yourself & get around 85% lean
3 oz finely grated monterey jack
1 1/2 cup mixed onion (2 small)
saute onions & celery in butter garlic & thyme
saltine crumbs 2/3 cup
gelatin 1/2 tsp bloomed in 1/2 cup chicken broth 2 eggs tsp paprika
tomatoe juice to scrape fond tbs soy sauce dijon parsley 3/4 tsp salt
1/4 tsp pepper

375 oven internal 135 before glazing
glaze: cook without glaze, then catsup, then catsup again (Hunt's)
plus cider vinigar gound coriander some heat
5 minutes into oven again, then glaze again
rest for 20 minutes

* PAN FRIED RED TATERS
red bliss, large enough to cut in half 1 1/2 to 3 inches
1 1/2 lb, give a quick rinse remove starch & set up to steam
olive oil in 12" skillet non-stick
cut side down about 6 min. for golden brown on cut side
flip and cook another 5 min.
lid on to steam & turn pan to low
1/4 tsp pepper, 1/4 tsp salt


* CORN BREAD BATTER

dry ingredients:
  3/4 cup AP flour
  3/4 cup corn meal
  3 tb sugar
  1/2 tsp salt
  3/4 tsp baking powder
  1/4 tsp baking soda

wet ingredients:
  3/4 cup buttermilk
  1 egg
  3tb melted butter, mild temp, at end

or cheap out:
  betty crocker or jiffy premix
  cans of chili, beans, sulsa, creamed corn (blah!)

* TAMALE PIE
450 pre-heated

bloom in 2 tb oil:
  2 tb chili powder
  fine-minced onion
  2 cloves garlic

filling cooked on stove top:
  14 1/2 oz fine dice or crushed tomato
  15 oz black beans washed
  1 lb 90% lean beef
  1/2 tsp salt
  1 cup freshly grated chedder cheese toward the end
  cilantro at the end

smooth out filling, corn bread on top, smooth out

cook for 10 to 15 minutes
check with wooden skewer for no crumbs
serve w/sour cream (goat yogurt?)
  
* EGGS
    eggs hold for a month+ in the fridge
    look at current julian date before shopping
    best non-stick: caphalon or all-clad
** scrambled
    2 eggs 8 in pan, 4 in 10 in pan, nonstick, should weight ~2.5 lb
    high heat
    1 tb milk per yoke
    1/16 tsp salt per yoke 
    foam tbs butter
** poached
    for 2 eggs:
    into boiling water non-stick 1 tb dist. white vinegar , off for 4 min
** hard-boiled
    inch of water above eggs just to a boil, then off-heat for 10 min
    ice water for 5 min, crack & roll & peel, dip egg in cold water to clean
** fried
    for 2 eggs:
    butter should foam immediately, when the foaming stops, cook
    2 1/2 minutes covered  (for 2 eggs)
    serve with Oscar Mayer bacon

* GARLIC POTATOES
pan toasted garlic
low flame, regular pan, unpeeled 25 min under cover, steam does the work
don't peel potatoes, russets, 5 cloves per tater
fork-tender, should not resist fork in or out
boil for about 25 min
1/4 stick per tater melted butter in first
1/2 & 1/2 milk, inexact about 1/2 cup per tater?
must be processed immediately
some salt

* STIR FRY
non-stick
hold hand inch over pan for 2 sec
sauce:
    3 tb minced ginger 
    3 tb tamari 
    chicken_stock 
    tb dry sherry 
    1/2 tsp sugar 
    (a bit of cornstarch)
    (lemonish stuff)

2tsp veg. oil until smoking,
throw pieces in separately about 2 min. each,
2tsp veg. oil for each batch
vege version: zuks, carrots, peppers
red onions, snow peas, basil at the end
scallions, garlic, ginger, aeromatics toward the end.
a minute or two all cooked together


* SOUFFLE (raspberry, lemon, grand marne)
5 eggs

#7 souffle bowl
grease inside of dish, then coat w/fine cocoa powder & sugar 30/70

** boue:
ap flower, 5 Tb
sugar 1/4 cup
pinch of salt
cup of milk
whisk smooth
cook on medium high about 3 min stirring, until turns into pudding
& pull away from side of pan

** in bowl
stir in 2 Tb butter
stir in 5 yokes
3 Tb Grand Marne
orange zest 1 Tb
5 egg yokes

** whites:
foam w/little cream of tartar
then add 1/4 cup sugar
whip to soft peaks
break surface tension on top
400 degrees for 20-25 minutes--delicate for about 10 mins.

* CUTTING BOARDS
totally bamboo congo board
    Not dishwasher treat every quarter w/mineral oil
Architect gripper plastic board

* recommends from Test Kitchen
sanyo 55 dollar rice cooker
feta cheese:  buy in brine  mt. Vikos 
vanilla ice cream:  Ben&Jerry   haagen-daz
spatulas:  wustof turner    oxo good grips    mator bourgous pelton

easy squeeze garlic squeezer 

* no stir risotto:
    heavy dutch oven
    2 cups rice
    1 cup white wine, absorb
    5 cups chicken broth, low sodium, some water
    15-20 minutes no stir, medium low
    1 cup broth, stir for 3 min.
    rest for 5 min
    1- cup parmison
    some butter chive, parsley, lemon juice, pepper


* to repair leaky gut:
remove sugar
remove diary, wheat, known allergens
quercetin&glutamine 1000 mg twice daily, each (x 6 wks)

* LEMON SOUFFLE FROM AMERICA'S TEST KITCHEN
5 large eggs
1/4 tsp cream of tartar & pinch of salt in whites
1/3 cup suger in both egg batches
1/3 cup lemon in yokes
2 tbs AP flour in yokes
temper the mix & into 10" steel skillet
cook on medium low, until cohesive & side bubbles
375 for 7-10 minutes

375 for 7-10 n

* FROM "HERBAL REMEDIES"
mullein
wintergreen
orris
california poppy
cramp bark (relaxing)
hawthorne blossoms/berries (strenghen the heart)
echanacea (immune boost)
periwinkle (astringent)
comfrey (wound healing)
yarrow  (wound healing)
self-heal (prunella ?) (immune boost)
garlic
milk thistle seed (preventing liver toxin)
ginko biloba (brain boost)
chasteberry (reduces testosterone, increases progesterone/estrogen)
  fennel (licorish lite) (digestive aid)
  catnip (anxiety)
pomegranate 
dandilion bitter (liver tonic, immune boost)
camomile (digestion)
feverfew (migraines)(euphoria)
yerba Mansa
passion flower (relaxant)
oregano margorim tarragon (immune boost)
foxglove (heart boost)
lavender (aroma therapy, antidepressant, wound healing)
artichoke (liver boost)
thyme (antiseptic, wound healing, immunity, digestion)
yucca (anti-inflammatory)
rosemary (digestion, brain boost, poor circulation)
mugwort 
lemon balm (astringent)
cactus fruit (diabetes)




* try these web sites:
    BudgetBytes.com
    Allrecipes
    Working Class Foodies

* Smitten Kitchen
Pioneer Woman 
Chow.com 
Serious Eats The Food Lab /u/J_Kenji_Lopez-Alt! <--check out his reddit posts).
/r/food, /r/cooking, /r/budgetfood, /r/askculinary, 
/r/cooking has a good FAQ on getting started, as well.
Sortedfood on utube

* mushroom classification:
    parasitic - eats living tissue
        lobster
    mycorrhizal - symbiotic w/tree roots
    saprobiotic - eats dead tissue
        shiitake
        maitake
        oyster
        lion's mane

* medicinal mushrooms:
    beech
    king trumpet
    shiitake
    maitake
    lion's mane
    
    chanterelles are high in nutrients
    lobsters are high in flavinoids?

* mushroom sources:
    www.oregonmushrooms.com
    www.wineforest.com
    www.dartagnan.com
    www.fat-of-the-land.blogspot.com
    www.marxfoods.com
    www.honest-food.net

* Scabies help:
    sunshine - sleeping away - obsessive cleaning - chanterelle
    cedarcide (Best Yet) & etc.
    oral ivermectin (apple horsepaste)
    Pomado de Azufre 10% cream & soap
    arm & hammer detergent
    dimethicone hair products
    Hot Shot pest strips
      powder mix:
        food grade diotomatious earth
        chelated sulphur
        cedar powder (from cedarcide)
    oils:
        neem
        lavender
        cedar
        tea tree
        eucalyptus

* Scabies prescription meds:
    permethrin for drenching
    triamcinolone acetonide ointment .1% for spot application 
    dermacerin for itching relief 
    check topix scabies forum

* BEST PRACTICE RISOTTO:
    Savignon Blanc,
    then Vermouth
    then Chardonney

* SEEDS TO TRY
Cherokee Purple heirloom tomatoe

* BEANS TO TRY
    vallarta
    rebosero

* BEAN SOURCES
    Native Seeds
    Seed Saver's Exchange
    Slow Food
