
* Scabies prescription meds:
    permethrin for drenching
    triamcinolone acetonide ointment .1% for spot application 
    dermacerin for itching relief 
    check topix scabies forum
    not tried yet:
        oral ivermectin (apple horsepaste)

* Scabies help:
    sunshine - sleeping away - obsessive cleaning - chanterelle
    cedarcide (Best Yet) & etc.
    Pomado de Azufre 10% cream & soap
    arm & hammer detergent
    dimethicone hair products
    Hot Shot pest strips
      powder mix:
        food grade diotomatious earth
        chelated sulphur
        cedar powder (from cedarcide)
    oils:
        neem
        lavender
        cedar
        tea tree
        eucalyptus

* FROM "HERBAL REMEDIES"
mullein
wintergreen
orris
california poppy
cramp bark (relaxing)
hawthorne blossoms/berries (strenghen the heart)
echanacea (immune boost)
periwinkle (astringent)
comfrey (wound healing)
yarrow  (wound healing)
self-heal (prunella ?) (immune boost)
garlic
milk thistle seed (preventing liver toxin)
ginko biloba (brain boost)
chasteberry (reduces testosterone, increases progesterone/estrogen)
  fennel (licorish lite) (digestive aid)
  catnip (anxiety)
pomegranate 
dandilion bitter (liver tonic, immune boost)
camomile (digestion)
feverfew (migraines)(euphoria)
yerba Mansa
passion flower (relaxant)
oregano margorim tarragon (immune boost)
foxglove (heart boost)
lavender (aroma therapy, antidepressant, wound healing)
artichoke (liver boost)
thyme (antiseptic, wound healing, immunity, digestion)
yucca (anti-inflammatory)
rosemary (digestion, brain boost, poor circulation)
mugwort 
lemon balm (astringent)
cactus fruit (diabetes)


* QUESTIONS
    can I get dental help from medicare?
    Jublia for toenail fungus?
    Would Good Feet help?
