* UNSORTED TODO
    
    season cast iron & english steel
    game of life in c in c & get back to Clark
    can I harvest more bamboo sticks at Pat's old house?
        "The Unit" from Pat
    check out "black mirror" on netflix
    movies to check out: "ex machina" & "fury road" & "batman: the dark knight"
        find film to go to with Gail    
    look into Good Feet
    get calendar 
    check out UPS store for real address (not PO box)
    Look into bitbucket & dropbox
    field straps & holsters for gun(s) / fresh ammo
    (done) get more steam mop pads (blue-ish subst. at Target)
    (done) white tape at andy&vax
    (done) get dad vet status
        get dad's card first monday in august
        chris on top of primary care doc once a year

* ELECTRONICS
    replace iTouch
    filter for big round air cleaner
    LG controller
    (done) get two more nice broadcast tv antennas (one at a time)
*** NEXT TO BATTERIES+
      spare battery for Clear device
      batteries for the little keychain knives?

* VEHICLES
    vet plates for white truck
        get real birth cert. from San Bernardina
    find/get red truck title
    (almost done) locking gas cap for white truck
    (done) strap for colt battery
    (done) switch for colt (It's panel light dimmer switch)

* HOUSEHOLD
    remove mold from back porch
    remote for LG

* PENDING QUESTIONS
    Can I send mail to drive.google.com? git?, bitbucket?, dropbox?
    Ask localvoirs if they know about super-eggs (not just free-range).
    can I get dental help from medicare?

* FOOD/KITCHEN:
  which foods should be refrigerated?
  re-organize fridge to allow for spices & herbs
  (done) himalayan sea salt at international grocers kitty-corner from powells

* CURRENT SHOPPING LIST
    hardware
        extra faucet branch
        new wipers for white truck
    grocery
        milk
        salsa ingredients
        fake/vegetarian oyster sauce
    kitchen
        big terra cotta garlic keepers
    sundries
        mouthwash
        Jublia for toenail fungus?
        check out Ped-egg to solve callus problem
    costco
        Nutribullet
        new iTouch
