* UNSORTED TODO
    game of life in c in c & get back to Clark
    get dad vet status
    get calendar 
    check out UPS store for real address (not PO box)
    Look into bitbucket & dropbox

* NEXT TO BATTERIES+
    spare battery for Clear device
    charger for dell computer

* VEHICLES
    locking gas cap for white truck
    new wipers for white truck
    colt to DEQ
    switch for colt
    strap for colt
    vet plates for white truck
    find/get red truck title

* HOUSEHOLD
    remove mold from back porch
    change lightbulbs in kitchen 
    check out Ped-egg to solve callus problem
    remote for LG

* PENDING QUESTIONS
    Can I send mail to drive.google.com? git?, bitbucket?, dropbox?
    Ask localvoirs if they know about super-eggs (not just free-range).
    can I get dental help from medicare?

* FOOD/KITCHEN:
  which foods should be refrigerated?
  himalayan sea salt at international grocers kitty-corner from powells
  find a real terra cotta garlic keeper
  (keeps garlic up to a month or two, per Cook's Illustrated)
  fake/vegetarian oyster sauce
